<div id="header-button">
		<ul>
			<!--<li><a href="view_gallery.php">View gallery</a></li>-->
			<li><a href="register.php">Register</a></li>
			<li><a href="login.php">Login</a></li>
			<!--<li><a href="admin_view_art.php">View Art</a></li>-->
			<!--<li><a href="admin_search.php">Search</a></li>-->
			</ul>
	</div>
<h1>The Dove Gallery</h1>
<h2>Affordable Original Paintings</h2>
<div id="logo">
	<img alt="dove" height="170" src="images/dove-1.png" width="234">
</div>