<div id="header-button">
		<ul>
			<li><a href="index.php">home Page</a></li>
		<form name="_xclick" target="paypal" 
action="https://www.paypal.com/uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="me@mybusiness.co.uk"> 
<input type="image" src="https://www.paypal.com/en_GB/i/btn/view_cart.gif" border="0" 
name="submit" alt="Make payments with PayPal - it's fast, free and secure!"> 
<input type="hidden" name="display" value="1">
</form>
			</ul>
	</div>
<h1>The Dove Gallery</h1>
<h2>Affordable Original Paintings</h2>
