<div class="col-sm-2">
<img class="img-fluid float-left" src="images/dove-1.png" alt="dove"> 
<!-- <img alt="dove" height="170" src="images/dove-1.png" width="234"> -->
</div>
<div class="col-sm-8">
 <h1 class="blue-text mb-4 font-bold">Header Goes Here</h1>
 </div>
     <nav class="col-sm-2">
	 <div class="btn-group-vertical btn-group-sm" id="header-button" role="group" aria-label="Button Group">
  <button type="button" class="btn btn-secondary" onclick="location.href = 'cart.php'" >View Cart</button>
  <button type="button" class="btn btn-secondary" onclick="location.href = 'index.php'" >Home Page</button>
  <button type="button" class="btn btn-secondary" onclick="location.href = 'logout.php'" >Logout</button>
</div>
    </nav>
	
	
<!--
<div id="header-button">
		<ul>
			<!--<li><a href="view_gallery.php">View gallery</a></li>
			<li><a href="search.php">Search</a></li>
			<li><a href="register.php">Register</a></li>
			<li><a href="admin_view_art.php">View Art</a></li>
			<li><a href="admin_search.php">Search</a></li>
			<li><a href="cart.php">View Cart</a></li>
			<li><a href="index.php">Home Page</a></li>
			<li><a href="logout.php">Logout</a></li>
		
		<!--<form name="_xclick" target="paypal" 
action="https://www.paypal.com/uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="me@mybusiness.co.uk"> 
<input type="image" src="https://www.paypal.com/en_GB/i/btn/view_cart.gif" border="0" 
name="submit" alt="Make payments with PayPal - it's fast, free and secure!"> 
<input type="hidden" name="display" value="1">
</form>
			</ul>
	</div>
<h1>The Dove Gallery</h1>
<h2>Affordable Original Paintings</h2>
<div id="logo">
	<img alt="dove" height="170" src="images/dove-1.png" width="234">
	</div>
	-->
	